kumuluzee:
  name: dostavca-driver
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  discovery:
    cluster: dostavca
    etcd:
      hosts: http://localhost:2379
    ttl: 20
    ping-interval: 15
